/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as OptimiseRouteImport } from './routes/optimise'
import { Route as HowWeTestedRouteImport } from './routes/how-we-tested'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FindMyPortfolioRouteImport } from './routes/find-my-portfolio'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundSchemeIdRouteImport } from './routes/fund.$schemeId'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimiseRoute = OptimiseRouteImport.update({
  id: '/optimise',
  path: '/optimise',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeTestedRoute = HowWeTestedRouteImport.update({
  id: '/how-we-tested',
  path: '/how-we-tested',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyPortfolioRoute = FindMyPortfolioRouteImport.update({
  id: '/find-my-portfolio',
  path: '/find-my-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundSchemeIdRoute = FundSchemeIdRouteImport.update({
  id: '/fund/$schemeId',
  path: '/fund/$schemeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/browse': typeof BrowseRoute
  '/find-my-portfolio': typeof FindMyPortfolioRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-we-tested': typeof HowWeTestedRoute
  '/optimise': typeof OptimiseRoute
  '/wizard': typeof WizardRoute
  '/fund/$schemeId': typeof FundSchemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/browse': typeof BrowseRoute
  '/find-my-portfolio': typeof FindMyPortfolioRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-we-tested': typeof HowWeTestedRoute
  '/optimise': typeof OptimiseRoute
  '/wizard': typeof WizardRoute
  '/fund/$schemeId': typeof FundSchemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/browse': typeof BrowseRoute
  '/find-my-portfolio': typeof FindMyPortfolioRoute
  '/how-it-works': typeof HowItWorksRoute
  '/how-we-tested': typeof HowWeTestedRoute
  '/optimise': typeof OptimiseRoute
  '/wizard': typeof WizardRoute
  '/fund/$schemeId': typeof FundSchemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/browse'
    | '/find-my-portfolio'
    | '/how-it-works'
    | '/how-we-tested'
    | '/optimise'
    | '/wizard'
    | '/fund/$schemeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/browse'
    | '/find-my-portfolio'
    | '/how-it-works'
    | '/how-we-tested'
    | '/optimise'
    | '/wizard'
    | '/fund/$schemeId'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/browse'
    | '/find-my-portfolio'
    | '/how-it-works'
    | '/how-we-tested'
    | '/optimise'
    | '/wizard'
    | '/fund/$schemeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  BrowseRoute: typeof BrowseRoute
  FindMyPortfolioRoute: typeof FindMyPortfolioRoute
  HowItWorksRoute: typeof HowItWorksRoute
  HowWeTestedRoute: typeof HowWeTestedRoute
  OptimiseRoute: typeof OptimiseRoute
  WizardRoute: typeof WizardRoute
  FundSchemeIdRoute: typeof FundSchemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimise': {
      id: '/optimise'
      path: '/optimise'
      fullPath: '/optimise'
      preLoaderRoute: typeof OptimiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-tested': {
      id: '/how-we-tested'
      path: '/how-we-tested'
      fullPath: '/how-we-tested'
      preLoaderRoute: typeof HowWeTestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-portfolio': {
      id: '/find-my-portfolio'
      path: '/find-my-portfolio'
      fullPath: '/find-my-portfolio'
      preLoaderRoute: typeof FindMyPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$schemeId': {
      id: '/fund/$schemeId'
      path: '/fund/$schemeId'
      fullPath: '/fund/$schemeId'
      preLoaderRoute: typeof FundSchemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  BrowseRoute: BrowseRoute,
  FindMyPortfolioRoute: FindMyPortfolioRoute,
  HowItWorksRoute: HowItWorksRoute,
  HowWeTestedRoute: HowWeTestedRoute,
  OptimiseRoute: OptimiseRoute,
  WizardRoute: WizardRoute,
  FundSchemeIdRoute: FundSchemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
